LineLength:
  Max: 120

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'Guardfile'

Metrics/AbcSize:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
